name: audit

on:
  pull_request

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm run setup
    - run: npx lerna exec --ignore @rsksmart/rlogin-dcent-provider --no-bail --parallel npm audit
    # - run: npm audit
