name: ci

on:
  pull_request
# Declare default permissions as read only.
permissions: read-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout
      uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e # v4.2.1
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Setup NodeJS
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - run: npm ci
    - run: npm run build
    - run: npm run test
    - run: npx lerna exec -- npm publish --dry-run
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
