name: ci

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Use Node.js 14.x
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0
      with:
        node-version: 22.x

    - run: npm ci
    - run: npm run build
    - run: npm run test
    - run: npx lerna exec -- npm publish --dry-run

    - name: Coveralls
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b #v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
