name: 'Dependency Review'
on: [pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e # v4.2.1

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
      - name: 'Create Summary File'
        run: echo "$GITHUB_STEP_SUMMARY" > dependency-review-summary.md
      - name: 'Split and Upload Summary'
        env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          split -b 1024k dependency-review-summary.md dependency-review-summary-part
          for part in dependency-review-summary-part*; do
            gh api repos/:owner/:repo/actions/workflows/:workflow_id/runs/:run_id/jobs/:job_id/steps/:step_id/summary --input $part
